export const postCategories =
{
  happy: [
    "happy",
    "grin",
    "beam",
    "chuckle",
    "chortle",
    "simper",
    "smirk",
    "sneer",
    "gleam",
    "radiate",
    "joyful",
    "joyous",
    "ecstatic",
    "elated",
    "jubilant",
    "blissful",
    "rapturous",
    "cheerful",
    "cheery",
    "merry",
    "jolly",
    "glad",
    "upbeat",
    "buoyant",
    "gleeful",
    "optimistic",
    "contented",
    "satisfied",
    "pleased",
    "serene",
    "tranquil",
    "euphoric",
    "exuberant",
    "delighted",
    "beaming",
    "lighthearted",
    "grateful",
    "thrilled",
    "overjoyed",
    "enthusiastic",
    "zestful",
    "elated",
    "giddy",
    "frolicsome",
    "bubbly",
    "lively",
    "sparkling",
    "vibrant",
    "chipper"
  ],
  sad: [
    "sad",
    "unhappy",
    "miserable",
    "wretched",
    "depressed",
    "despondent",
    "dejected",
    "downcast",
    "gloomy",
    "melancholy",
    "sorrowful",
    "grief-stricken",
    "heartbroken",
    "distraught",
    "forlorn",
    "desolate",
    "lonesome",
    "solitary",
    "isolated",
    "estranged",
    "alienated",
    "abandoned",
    "forsaken",
    "weep",
    "sob",
    "bawl",
    "blubber",
    "wail",
    "moan",
    "groan",
    "lament",
    "grieve",
    "mourn",
    "keen",
    "snivel",
    "whimper",
    "boohoo",
    "downhearted",
    "dismal",
    "blue",
    "woeful",
    "disheartened",
    "devastated",
    "hollow",
    "brokenhearted",
    "despairing",
    "tragic",
    "lugubrious",
    "pained",
    "sullen",
    "disconsolate",
    "inconsolable",
    "wistful",
    "tearful",
    "heavy-hearted",
    "low-spirited",
    "in the dumps",
    "doleful",
    "heartache",
    "anguish",
    "tormented"
  ],
  angry: [
    "mad",
    "rage",
    "fury",
    "wrath",
    "outrage",
    "indignation",
    "irritation",
    "annoyance",
    "exasperation",
    "resentment",
    "ire",
    "displeasure",
    "vexation",
    "pique",
    "spleen",
    "hostility",
    "bitterness",
    "acrimony",
    "choler",
    "fuming",
    "seething",
    "lividity",
    "temper",
    "furore",
    "furor",
    "ballistic",
    "infuriation",
    "enragement",
    "aggravation",
    "chagrin",
    "belligerence",
    "riled",
    "maddened",
    "wrathful",
    "frenzy",
    "steam",
    "red-faced",
    "fury-driven",
    "huff",
    "cross",
    "cranky",
    "testy",
    "irascible",
    "short-tempered",
    "temperamental",
    "blazing",
    "rant",
    "yelling",
    "snarling"
  ],
  tech: [
    "future",
    "tomorrow",
    "futuristic",
    "innovation",
    "invention",
    "progress",
    "advancement",
    "next-gen",
    "cutting-edge",
    "breakthrough",
    "visionary",
    "forecast",
    "prospect",
    "foresight",
    "speculation",
    "possibility",
    "utopia",
    "singularity",
    "cybernetic",
    "space-age",
    "hi-tech",
    "ai",
    "automation",
    "autonomous",
    "robotics",
    "drones",
    "chatbots",
    "algorithms",
    "data science",
    "big data",
    "iot",
    "5g",
    "blockchain",
    "cryptocurrency",
    "metaverse",
    "smart cities",
    "wearables",
    "biohacking",
    "genetic engineering",
    "synthetic biology",
    "nanotechnology",
    "cybersecurity",
    "digital transformation",
    "tech-driven",
    "disruption",
    "tech-savvy",
    "transhumanism",
    "superintelligence",
    "neurotechnology",
    "holograms"
  ],

  news: [
    "news",
    "headline",
    "breaking news",
    "latest",
    "update",
    "report",
    "bulletin",
    "coverage",
    "story",
    "article",
    "feature",
    "editorial",
    "op-ed",
    "column",
    "dispatch",
    "newsflash",
    "exclusive",
    "investigation",
    "newsroom",
    "correspondent",
    "reporter",
    "journalist",
    "anchor",
    "newscaster",
    "broadcaster",
    "media",
    "publisher",
    "network",
    "press",
    "newswire",
    "breaking",
    "developing story",
    "fact-checking",
    "misinformation",
    "disinformation",
    "censorship",
    "investigative journalism",
    "photojournalism",
    "infographic",
    "viral",
    "trending",
    "sensational",
    "clickbait",
    "headline-grabbing",
    "leaked",
    "eyewitness",
    "testimony",
    "interview",
    "soundbite",
    "broadcast",
    "telecast",
    "livestream",
    "podcast",
    "current events",
    "alternative media"
  ],
  love: [
    "love",
    "romance",
    "dating",
    "infatuation",
    "affection",
    "adoration",
    "attraction",
    "passion",
    "desire",
    "crush",
    "flirtation",
    "flirting",
    "courtship",
    "relationship",
    "soulmate",
    "significant other",
    "partner",
    "couple",
    "boyfriend",
    "girlfriend",
    "lover",
    "romantic",
    "chemistry",
    "embrace",
    "hug",
    "kiss",
    "smitten",
    "enamored",
    "devotion",
    "tenderness",
    "caring",
    "heartfelt",
    "sweetheart",
    "darling",
    "beloved",
    "affair",
    "heartthrob",
    "butterflies",
    "longing",
    "admiration",
    "lovebirds",
    "cuddle",
    "snuggle",
    "connection",
    "compatibility",
    "emotional bond",
    "intimacy",
    "trust",
    "commitment",
    "heartache",
    "love-struck",
    "desiring",
    "match",
    "tinder"
  ],

}

export const prepositions = [
  "aboard", "about", "above", "absent", "across", "after", "against", "along", "alongside", "amid", "amidst",
  "among", "amongst", "around", "as", "aside", "astride", "at", "athwart", "atop", "barring", "before",
  "behind", "below", "beneath", "beside", "besides", "between", "beyond", "but", "by", "circa", "concerning",
  "considering", "despite", "down", "during", "except", "excluding", "failing", "following", "for",
  "from", "given", "in", "including", "inside", "into", "less", "like", "minus", "near", "notwithstanding",
  "of", "off", "on", "onto", "opposite", "out", "outside", "over", "past", "per", "plus", "pro", "regarding",
  "round", "save", "since", "than", "through", "throughout", "till", "to", "toward", "towards", "under",
  "underneath", "unlike", "until", "up", "upon", "versus", "via", "with", "within", "without", "worth", "no", "one", "had"
]

export type PostCategoryType = typeof postCategories;